main.c
void MainMenu()
References EXIT.
Referenced by main.
void PrintWelcomeMsg()
References Utils_Delay.
Referenced by main.
void PrintGoodbyeMsg()
References Utils_Delay.
Referenced by main.
void Utils_Delay(int iSeconds)
Referenced by PrintGoodbyeMsg, PrintWelcomeMsg.
int main()
References MainMenu, PrintGoodbyeMsg, PrintWelcomeMsg.